Repository wakatime/wakatime-cli, pull requests merged in 2021-05, with the labels that each got.

#335 Fix CONTRIBUTING link
  README.md
Labels: bug

#336 Fix title case
  README.md
Labels: bug

#293 Apply label on new issues
  .github/workflows/on_open_issue.yml
Labels: p2

#341 Add test for multine submodules
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  pkg/project/subversion_test.go
Labels: feature, p0

#343 Add name to on_open_issue workflow
  .github/workflows/on_open_issue.yml
Labels: feature, p1

#339 Create LICENSE
  LICENSE
Labels: p0

#348 Remove welcome message on open issue
  .github/workflows/on_open_issue.yml
Labels: feature, p2

#345 D-F verified language constants
  pkg/heartbeat/language.go
  pkg/heartbeat/language_test.go
Labels: feature, p0

#356 Update chroma to latest version v0.8.2-wakatime.7
  go.mod
  go.sum
  pkg/heartbeat/language.go
  pkg/heartbeat/language_test.go
Labels: p0

#354 Mark deprecated flags
  cmd/root.go
Labels: feature

#350 Update allowed branch pattern
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_protected_branches.yml
Labels: p0

#353 Fix alternate-language param info
  cmd/root.go
Labels: p0

#358 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: p0

#357 Changes for v1
  pkg/version/version.go
Labels: p0

#351 Develop into Master
  .github/workflows/on_open_issue.yml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push.yaml
  .github/workflows/on_push.yml
  .github/workflows/on_push_protected_branches.yml
  .github/workflows/on_push_windows.yaml
  .github/workflows/on_release.yaml
  .goreleaser.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  Makefile
  README.md
  bin/prepare_assets.sh
  cmd/generate/main.go
  cmd/legacy/heartbeat/heartbeat.go
  cmd/legacy/heartbeat/heartbeat_test.go
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  cmd/legacy/heartbeat/testdata/extra_heartbeats.json
  cmd/legacy/logfile/logfile.go
  cmd/legacy/run.go
  cmd/root.go
  go.mod
  go.sum
  pkg/api/heartbeat_test.go
  pkg/deps/deps.go
  pkg/deps/deps_test.go
  pkg/deps/golang.go
  pkg/filter/filter_test.go
  pkg/heartbeat/heartbeat.go
  pkg/heartbeat/heartbeat_test.go
  pkg/heartbeat/language.go
  pkg/heartbeat/language_test.go
  pkg/heartbeat/sanitize_test.go
  pkg/language/language.go
  pkg/language/language_test.go
  pkg/language/plugins.go
  pkg/language/plugins/README.md
  pkg/language/plugins/default.json
  pkg/language/plugins/vim.json
  pkg/language/plugins_test.go
  pkg/language/testdata/codefiles/unknown.xyz
  pkg/language/vim.go
  pkg/language/vim_internal_test.go
  pkg/log/log.go
  pkg/offline/offline_test.go
  pkg/project/subversion_test.go
  pkg/version/version.go
Labels: p0

#361 Fix infinite loop for Windows
  pkg/project/git.go
  pkg/project/mercurial.go
Labels: bug, p0

#366 Hide deprecated flags
  cmd/root.go
Labels: p0

#362 Log improvements
  Makefile
  cmd/legacy/logfile/logfile.go
  cmd/legacy/logfile/logfile_test.go
  cmd/legacy/run.go
  cmd/root.go
  pkg/deps/deps.go
  pkg/filestats/filestats.go
  pkg/filter/filter.go
  pkg/heartbeat/sanitize.go
  pkg/language/language.go
  pkg/offline/offline.go
  pkg/project/project.go
Labels: p1

#338 Add coverage report
  .github/workflows/on_push.yml
  .github/workflows/on_push_protected_branches.yml
  Makefile
  README.md
Labels: p1

#370 Replace recursive calls by for while loops
  pkg/project/file.go
  pkg/project/git.go
  pkg/project/mercurial.go
  pkg/project/subversion.go
Labels: feature, p0

#375 Fix PR documentation in CONTIBUTING
  CONTRIBUTING.md
Labels: p2

#377 Update semver to v1.2.2
  .github/workflows/on_push_protected_branches.yml
Labels: p0

#376 Add configuring section to README
  CONFIGURING.md
  README.md
  cmd/root.go
Labels: p2

#368 Add integration tests
  .github/workflows/on_push.yml
  .github/workflows/on_push_protected_branches.yml
  Makefile
  cmd/legacy/run.go
  main_test.go
  testdata/api_goals_id_response.json
  testdata/api_heartbeats_request.json.tpl
  testdata/api_heartbeats_response.json
  testdata/api_summaries_response.json.tpl
  testdata/main.go
  testdata/wakatime.cfg
Labels: p0

#372 Add TFVC Project Detection
  pkg/project/file.go
  pkg/project/git.go
  pkg/project/git_test.go
  pkg/project/mercurial.go
  pkg/project/mercurial_test.go
  pkg/project/project.go
  pkg/project/subversion.go
  pkg/project/subversion_test.go
  pkg/project/tfvc.go
  pkg/project/tfvc_test.go
Labels: feature, p2

#378 Refactor git project detection
  pkg/project/git.go
Labels: p2

#379 v1.6.0 Release
  .github/workflows/on_push.yml
  .github/workflows/on_push_protected_branches.yml
  CONFIGURING.md
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/legacy/logfile/logfile.go
  cmd/legacy/logfile/logfile_test.go
  cmd/legacy/run.go
  cmd/root.go
  main_test.go
  pkg/deps/deps.go
  pkg/filestats/filestats.go
  pkg/filter/filter.go
  pkg/heartbeat/sanitize.go
  pkg/language/language.go
  pkg/offline/offline.go
  pkg/project/file.go
  pkg/project/git.go
  pkg/project/git_test.go
  pkg/project/mercurial.go
  pkg/project/mercurial_test.go
  pkg/project/project.go
  pkg/project/subversion.go
  pkg/project/subversion_test.go
  pkg/project/tfvc.go
  pkg/project/tfvc_test.go
  testdata/api_goals_id_response.json
  testdata/api_heartbeats_request.json.tpl
  testdata/api_heartbeats_response.json
  testdata/api_summaries_response.json.tpl
  testdata/main.go
  testdata/wakatime.cfg
Labels: p0

#382 Update semver to v1.3.0
  .github/workflows/on_push.yml
Labels: p0

#386 Update semver to v1.3.1
  .github/workflows/on_push.yml
Labels: p0

#383 Improve makefile
  .github/workflows/on_push.yml
  CONTRIBUTING.md
  Makefile
Labels: p1

#381 Configure jww to capture logs from viper
  cmd/legacy/run.go
  go.mod
  pkg/log/log.go
Labels: do not merge, feature, p0

#389 Strip quotes from parameters
  pkg/vipertools/vipertools.go
Labels: p0

#390 Add GetString to vipertools
  cmd/legacy/configread/configread.go
  cmd/legacy/configwrite/configwrite.go
  cmd/legacy/heartbeat/params.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/run.go
  cmd/legacy/todaygoal/todaygoal.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/vipertools/vipertools.go
  pkg/vipertools/vipertools_test.go
Labels: bug, p0

#397 Delete unused history file
  HISTORY.rst
Labels: p2

#400 Set the target commit for releasing
  .github/workflows/on_push.yml
Labels: bug

#401 Update semver to v1.3.2
  .github/workflows/on_push.yml
Labels: p0

#395 Control http.Client creation instead of using http.DefaultClient
  cmd/legacy/heartbeat/heartbeat.go
  cmd/legacy/today/today.go
  cmd/legacy/todaygoal/todaygoal.go
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/goal_test.go
  pkg/api/heartbeat_test.go
  pkg/api/option_test.go
  pkg/api/summary_test.go
  pkg/api/transport.go
Labels: bug

#408 Merge on_release workflow into on_push
  .github/workflows/on_push.yml
  .github/workflows/on_release.yaml
Labels: feature

#414 Move api client initialization into api package
  cmd/legacy/heartbeat/heartbeat.go
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  cmd/legacy/legacyapi/api.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/legacyparams/params_test.go
  cmd/legacy/today/today.go
  cmd/legacy/today/today_test.go
  cmd/legacy/todaygoal/todaygoal.go
  cmd/legacy/todaygoal/todaygoal_test.go
  go.sum
Labels: p0

#428 Add concurrency attribute to avoid claiming the same version
  .github/workflows/on_push.yml
Labels: bug

#421 Add distinct sync-offline-activity command
  cmd/legacy/offlinesync/offlinesync.go
  cmd/legacy/offlinesync/offlinesync_test.go
  cmd/legacy/offlinesync/testdata/api_heartbeats_request_template.json
  cmd/legacy/offlinesync/testdata/api_heartbeats_response.json
  cmd/legacy/offlinesync/testdata/heartbeat_go.json
  cmd/legacy/offlinesync/testdata/heartbeat_js.json
  cmd/legacy/offlinesync/testdata/heartbeat_py.json
  cmd/legacy/run.go
  pkg/offline/offline.go
Labels: bug

#409 Prevent using DefaultTransport
  draft/usage.md
  pkg/api/option.go
  pkg/api/transport.go
Labels: bug

#431 Spawn multiple threads to build faster
  .github/workflows/on_push.yml
Labels: feature

#434 Show help as fallback
  cmd/legacy/run.go
  cmd/root.go
Labels: feature
