Repository wakatime/wakatime-cli, pull requests merged in 2021-06, with the labels that each got.

#433 Separate changelog for develop and release
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/develop.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/workflows/on_push.yml
Labels: feature

#438 Ensure error response parsing for 4xx and 5xx heartbeat response errors
  pkg/api/heartbeat.go
  pkg/api/heartbeat_test.go
  pkg/api/testdata/api_heartbeats_response_error.json
  pkg/api/testdata/api_heartbeats_response_errors.json
Labels: bug

#439 Do not use default offline queue file in integration tests
  cmd/legacy/heartbeat/heartbeat.go
  cmd/legacy/heartbeat/params.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/legacyparams/params_test.go
  cmd/root.go
  go.mod
  main_test.go
Labels: bug

#444 Lower default offline sync level
  cmd/root.go
Labels: p1

#443 Fix changelog for Slack notification
  .github/workflows/on_push.yml
Labels: bug

#447 Add double quotes to changelog variable
  .github/workflows/on_push.yml
Labels: bug

#448 Break single quote for replace string
  .github/workflows/on_push.yml
Labels: bug

#436 Send diagnostic info on heartbeat, today and todaygoal commands
  cmd/legacy/configread/configread.go
  cmd/legacy/configread/configread_test.go
  cmd/legacy/configread/error.go
  cmd/legacy/configwrite/configwrite.go
  cmd/legacy/configwrite/configwrite_test.go
  cmd/legacy/error.go
  cmd/legacy/heartbeat/heartbeat.go
  cmd/legacy/legacyapi/api.go
  cmd/legacy/offlinesync/offlinesync.go
  cmd/legacy/run.go
  cmd/legacy/run_test.go
  cmd/legacy/testdata/diagnostics_request_template.json
  cmd/legacy/today/today.go
  cmd/legacy/todaygoal/todaygoal.go
  cmd/legacy/version.go
  pkg/api/diagnostic.go
  pkg/api/diagnostic_test.go
  pkg/api/testdata/diagnostics_request.json
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/error.go
  pkg/diagnostic/diagnostic.go
  pkg/log/log.go
Labels: p0

#441 Expand users home dir for input flags
  USAGE.md
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/legacyparams/params_test.go
  cmd/legacy/logfile/logfile.go
  pkg/api/option.go
  pkg/filestats/filestats.go
Labels: feature

#451 Support legacy api_url param format by removing endpoint from url
  cmd/legacy/heartbeat/heartbeat_test.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/legacyparams/params_test.go
  cmd/legacy/offlinesync/offlinesync_test.go
  cmd/legacy/run_test.go
  cmd/legacy/today/today_test.go
  cmd/legacy/todaygoal/todaygoal_test.go
  cmd/root.go
  main_test.go
  pkg/api/api.go
  pkg/api/diagnostic.go
  pkg/api/diagnostic_test.go
  pkg/api/goal.go
  pkg/api/goal_test.go
  pkg/api/heartbeat.go
  pkg/api/heartbeat_test.go
  pkg/api/summary.go
  pkg/api/summary_test.go
Labels: bug

#452 Use go env var for all steps
  .github/workflows/on_push.yml
Labels: p2

#453 Distinct offline sync function (send all queued preparation pt1)
  cmd/legacy/offlinesync/offlinesync.go
  pkg/api/heartbeat.go
  pkg/api/heartbeat_test.go
  pkg/heartbeat/heartbeat.go
  pkg/heartbeat/heartbeat_test.go
  pkg/offline/offline.go
  pkg/offline/offline_test.go
Labels: p0

#454 Remove offline sync from heartbeats pipeline (send all queued preparation pt2)
  cmd/legacy/run.go
  cmd/legacy/run_test.go
  cmd/legacy/testdata/api_heartbeats_request.json
  cmd/legacy/testdata/api_heartbeats_response.json
  cmd/legacy/testdata/diagnostics_request_template_no_logs.json
  cmd/legacy/testdata/heartbeat_go.json
  cmd/legacy/testdata/heartbeat_py.json
  pkg/offline/offline.go
  pkg/offline/offline_test.go
Labels: p0

#456 Remove viper fork dependency
  go.mod
  go.sum
Labels: p2

#455 Send all queued heartbeats in offline sync
  cmd/legacy/heartbeat/heartbeat_test.go
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  cmd/legacy/legacyparams/params_test.go
  cmd/legacy/today/today_test.go
  cmd/legacy/todaygoal/todaygoal_test.go
  cmd/root.go
  pkg/offline/offline.go
  pkg/offline/offline_test.go
Labels: feature

#461 Add hostname to API request
  cmd/legacy/heartbeat/params.go
  cmd/legacy/heartbeat/params_test.go
  cmd/legacy/legacyapi/api.go
  cmd/legacy/legacyparams/params.go
  cmd/legacy/legacyparams/params_test.go
  pkg/api/diagnostic.go
Labels: feature

#469 Log warning on system cert pool error
  pkg/api/transport.go
Labels: feature

#465 New --offline-count argument
  README.md
  cmd/legacy/offlinecount/offlinecount.go
  cmd/legacy/offlinecount/offlinecount_test.go
  cmd/legacy/run.go
  cmd/root.go
  main_test.go
  pkg/offline/offline.go
  pkg/offline/offline_test.go
Labels: feature

#468 Prevent writing to default log file in integration tests
  main_test.go
Labels: bug
